<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Promises in JS</title>
  </head>
  <body style="background-color: aqua">
    <h1>Lets Study Promises in JS</h1>

    <script>
      // PROMISES IN JAVASCRIPT :  used to simplify Callback Hell problem

      // Promise is for “eventual” completion of task. It is an object in JS.
      // Syntax :  let promise = new Promise( (resolve, reject) => { .... } )
      // here, "resolve" and "reject" are Handlers OR two default callback functions provided by JS
      // If resolve() is run, it means Promise is fulfilled and Resolved :)
      // if reject() is run, it means Promise is fulfilled but Rejected :(

      let promise = new Promise(() => {
        console.log("I am a Promise");
      });

      // if we console.log(promise)
      // we get
      /*
        Promise {<pending>}
        [[Prototype]]
        :
        Promise
        [[PromiseState]]
        :
        "pending"
        [[PromiseResult]]
        :
        undefined
        */

      // A promise can Have 3 states :
      // 1. Pending State
      // 2. Fulfilled State (resolved state)
      // 3. Rejected State

      console.log(promise);
      // Here it shows PENDING state of a promise

      let promise2 = new Promise((resolve, reject) => {
        console.log("I am promise2");
        resolve("SUCCESS..!   SUIII....");
      });

      console.log(promise2);
      // Here it shows RESOLVED state of a promise

      let promise3 = new Promise((resolve, reject) => {
        console.log("I am Promise3");
        reject("Fail due to Network Error");
      });

      console.log(promise3);
      // Here it shows REJECTED state of a promise

      // use of promises in general programming ???
      // Consider : The API's(here getData2 function) returning us promises

      function getData2(dataId, nextData) {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            console.log("Data is : ", dataId);
            resolve("Success SUIIII..");
            if (nextData) {
              nextData();
            }
          }, 5000);
        });
      }

      // whenever we call getData2(123)  , it will immediately return us a promise and after 5sec it prints our required data
      // Here , we can call the getData2 funct , we will get a promise immedaiately but no any result
      // so , immediately when we check it , our Promise = PENDING
      // after 5s, when data is printed , work done succesfully , if we check promise, our Promise = SUCCESS

      /* THE OUTPUT IS AS FOLLOWS :
        let res = getData2(123) ;

        res;
        Promise {<pending>}[[Prototype]]: Promise[[PromiseState]]: "fulfilled"[[PromiseResult]]: "Success SUIIII.."

        twelve.js:186 Data is :  123

        res;
        Promise {<fulfilled>: 'Success SUIIII..'} */

      /*
        A JavaScript Promise object can be:
        Pending : the result is undefined
        Resolved : the result is a value (fulfilled)   resolve( result )
        Rejected : the result is an error object        reject( error ) */

      // A promise gets Fulfilled OR gets rejected isnt in our Hand, but we must know how to handle promises or work with promises then after
      // using .then() and .catch()

      /*
        .then( ) & .catch( )
        promise.then( ( res ) => { .... } )
        promise.catch( ( err ) ) => { .... } )*/

      // .then() is used after a Promise is completed/Resolved
      // .catch() is used after a Promise is Failed/Rejected

      // .then( 'any function xyz' )
      // this xyz function will only execute if the promise is resolved

      //   const getResolvedPromise = () => {
      //     return new Promise((resolve, reject) => {
      //       console.log("I am the latest promise used to study .then()");
      //       resolve("Adios ..!");
      //     });
      //   };

      //   let myPromise = getResolvedPromise();
      //   myPromise.then(() => {
      //     console.log("I am displayed bcoz myPromise is succefully resolved");
      //   });

      //   const getRejectedPromise = () => {
      //     return new Promise((resolve, reject) => {
      //       console.log("I am the latest promise used to study .catch()");
      //       reject("Rejected to check .catch() statement");
      //     });
      //   };

      //   let myPromise2 = getRejectedPromise();
      //   myPromise2.catch(() => {
      //     console.log("I am displayed bcoz myPromise2 is  REJECTED");
      //   });

      // PROMISES WITH ASYNC FUNCTION

      function async1() {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            console.log("First Data ");
            resolve("Success Suii");
          }, 6000);
        });
      }

      function async2() {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            console.log("Second Data ");
            resolve("Success Suii");
          }, 6000);
        });
      }

      //   console.log("Fetching Data 1");
      //   let a = async1();
      //   a.then((res) => {
      //     console.log(res);
      //   });

      //   console.log("Fetching Data 2");
      //   let b = async2();
      //   b.then((res) => {
      //     console.log(res);
      //   });

      // We wanted that,
      /*
              Fetching Data 1
              First Data.. 
              ..after 6sec..
              console.log(res); =>Success Suii
              Fetching Data 2
              .. afetr 6sec ..
              console.log(res); =>Success Suii */

      // BUt we get :
      /*
      Fetching Data 1
      Fetching Data 2
 ..after 6 sec... all together
      First Data.. 
      Success Suii
      Second Data.. 
      Success Suii
     */

      // FOR OUR REQUIRED OUTPUT : WE WILL USE "PROMISE CHAINING"
      // .then ke ander ek aur .then
      // pehla promise resolve ho tabhi dusre data ke liye search ho

      console.log("...Fetching Data 1...");
      async1().then((res) => {
        console.log(res);
        console.log("...Fetching Data 2...");
        async2().then((res) => {
          //This is PROMISE CHAINING
          console.log(res);
        });
      });

      // Solving our Callback HELL problem using PROMISE

      function getData(dataId) {
        setTimeout(() => {
          console.log("The Data is : ", dataId);
        }, 3000);
      }

      function callbackHell(dataId, nextData) {
        setTimeout(() => {
          console.log("The Data is : ", dataId);
          if (nextData) {
            nextData();
          }
        }, 3000);
      }

      callbackHell(2, () => {
        console.log("Getting Data 3 ....");
        callbackHell(3, () => {
          console.log("Getting Data 4 ...."); // This is the "PYRAMID OF DOOM"
          callbackHell(4, () => {
            console.log("Getting Data 5 ....");
            callbackHell(5);
          });
        });
      });
    </script>
  </body>
</html>
